### ISSUE TITLE
Convert to MR again

### ISSUE THREAD

**Issue by CashOver** [charlieamer/TwistedMetal4Parser#1]
Hi, I would like to know how I can re-transform the file that was extracted and turn it back into MR from Twister Metal 4

**Comment by charlieamer** [comment]
Thank you for the interest and sorry for doing this so slowly, i had some unexpected problems with code. I've finished it. You can find necessary tools in releases ([here](https://github.com/charlieamer/TwistedMetal4Parser/releases)) and read about them in more detail in readme file ([here](https://github.com/charlieamer/TwistedMetal4Parser#other-utilities)). Feel free to reopen this issue if you have any troubles.
