### ISSUE TITLE
System error

### ISSUE THREAD

**Issue by CashOver** [charlieamer/TwistedMetal4Parser#2]
Hi, I would like to say that you are having a problem when you are going to run the program every time with the main errors are:
cygwin1.dll
cyggcc_s-seh-1.dll
cygstdc++-6.dll
I would like to know how to solve it, I apologize for what happened

**Comment by charlieamer** [comment]
@CashOver sorry for delayed answer. Can you try with new binaries now ? I've uploaded them in releases section.
EDIT: They should be under same release (v1.2)

**Comment by charlieamer** [comment]
This should be fixed in latest release v1.2 now
