### ISSUE TITLE
Error Continues

### ISSUE THREAD

**Issue by CashOver** [charlieamer/TwistedMetal4Parser#3]
Hi I would like to say that the program is giving the same error now is: 
- libgcc_s_seh-1.dll 
-  libstdc++-6.dll
- libwinpthread-1 
But I also don't know why it is causing error 0xc000007b because my drives are working fine, just to let you know. thank you very much for your help and I'm sorry if I'm in the way.

**Comment by charlieamer** [comment]
This should be fixed in latest release v1.2 now

**Comment by CashOver** [comment]
Thanks
